name: Build
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  # Trigger for changes in the whatwg/sg repo.
  repository_dispatch:
    types:
    - sg_repo_updated
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: pip install -r requirements.txt
    - run: npm install
    - run: shellcheck deploy.sh
    - run: shellcheck resources.whatwg.org/build/*.sh
    - run: bash ./deploy.sh
      env:
        SERVER: ${{ secrets.MARQUEE_SERVER }}
        SERVER_PUBLIC_KEY: ${{ secrets.MARQUEE_PUBLIC_KEY }}
        SERVER_DEPLOY_KEY: ${{ secrets.MARQUEE_DEPLOY_KEY }}
